### ISSUE TITLE
amd 64 version 

### ISSUE THREAD

**Issue by ardenking** [Batrium/WatchMonUdpListener#15]
hi this isn't running for me but my system isnt running on arm is there used to be a pc version but can't find it

**Comment by jbates58** [comment]
> hi this isn't running for me but my system isnt running on arm is there used to be a pc version but can't find it

yes, there is an amd64 version.

its on docker hub.

i use either one of the below to run it under docker. Although im still working throught the issue in the compose file where it seems to need to be set to the host network; and its not working by exposing the ports. I am unsure why this is, but have not put a lot of time into investigating the issue. Perhaps @daromer2 may chime in and tell us.

But, at least this will get you operational on a x86 platform

Docker Run:
```
docker run --name=watchmon --log-opt max-size=10m --network=host --restart=always -itd -v batrium:/app/config daromer/watchmonudplistener:amd64
```


Docker Compose:
```
#########################################################################
#
#                    IMPORTANT NOTES FOR SUCCESS
#
# Start the container by running docker-compose up -d, after the initial
# pull and running of the container, stop it and then modify the config.json
# file in this directory as required, and then copy it into the created
# volume for the container; it should be located in
#
# /var/lib/docker/volumes/watchmon_listener_batrium/_data/config.json
#
# you will need sudo privs to access that location. After this, restart
# the container service with docker-compose up -d and it should be fully
# operational and sending the data out via MQTT and into the specified InfluxDB
#
#########################################################################

version: '2.3'

services:
  watchmon_listener:
    image: daromer/watchmonudplistener:amd64
    container_name: Watchmon_UDP_Listener
    network_mode: host
    restart: always
    volumes:
      - batrium:/app/config


# Im still working on this, as im not sure why it wont work with the ports exposed. It seems to need to be in host mode
#    ports:
#      - 18542:18542

    logging:
      options:
        max-size: "5m"
        max-file: "1"

volumes:
  batrium:
```
